version: "3.7"

services:
  postgres:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chalmers
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
